// ***************************************************************
//  zdp_base_proto   version:  1.0                         
//  ------------------------------------------------------------ 
//  This file was generated by vxgen.exe, don't manually modify.   
//  Hangzhou Zhidu Network Ltd.  (admin@zhidu.biz)               
//  Copyright (C) 2013-2017 - All Rights Reserved
// *************************************************************** 

#pragma once
#ifndef _zdp_base_proto_h_
#define _zdp_base_proto_h_

#include <zce/zce_config.h>
#include <zce/zce_smartptr.h>
#include <zce/zce_types.h>

namespace zdp_base
{
    enum ERV_ZDP_ERRO
    {
        ZDP_ERRO_BASE = 0x80001000,
        ZDP_ERRO_NOTFOUND = 0x80001001,
        ZDP_ERRO_BADSERVICE = 0x80001002,
        ZDP_ERRO_BADARG = 0x80001003,
        ZDP_ERRO_BADPRIV = 0x80001004,
        ZDP_ERRO_BADAUTH = 0x80001005,
    };

    enum IE_E
    {
        E_IE_RESULT = 0x00000010 /*前面16个IE保留*/,
        E_IE_CHAR = 0x00000011,
        E_IE_BYTE = 0x00000012,
        E_IE_INT16 = 0x00000013,
        E_IE_UINT16 = 0x00000014,
        E_IE_INT32 = 0x00000015,
        E_IE_UINT32 = 0x00000016,
        E_IE_INT64 = 0x00000017,
        E_IE_STRING254 = 0x00000018,
        E_IE_STRING = 0x00000019,
        E_IE_STRING_UTF8 = 0x00000019,
        E_IE_ANY = 0x0000001a,
        E_IE_PROP = 0x0000001b,
        E_IE_UALOGIN = 0x0000001c,
        E_IE_SITE = 0x0000001d,
        E_IE_USERSITE = 0x0000001e,
        E_IE_INT64VEC = 0x0000001f,
        E_IE_RESULT_EX = 0x00000020,
        E_IE_NSPAIR = 0x00000021,
        E_IE_NIPAIR = 0x00000022,
        E_IE_NLLPAIR = 0x00000023,
        E_IE_SITEID = 0x00000024,
        E_IE_NETADDR = 0x00000025,
    };

    enum MSG_E
    {
        E_MSG_NONE_REQ = 0x00000000,
        E_MSG_CONN_REQ = 0x00000002,
        E_MSG_DISCONN_REQ = 0x00000004,
    };

    struct zdp_addr_t
    {

        zdp_addr_t()
        :translayer(0)
        ,ipclass(0)
        ,port(0)
        {
        }

        zce_byte    translayer;
        zce_byte    ipclass;
        zce_uint16    port;
        zce_astring addr;
    };
    struct IE_RESULT
    {
        const static unsigned short IE_TYPE = E_IE_RESULT;

        IE_RESULT()
        :error_code(0)
        {
        }

        zce_int32    error_code;
    };
    struct IE_CHAR
    {
        const static unsigned short IE_TYPE = E_IE_CHAR;

        IE_CHAR()
        :val(0)
        {
        }

        zce_char    val;
    };
    struct IE_BYTE
    {
        const static unsigned short IE_TYPE = E_IE_BYTE;

        IE_BYTE()
        :val(0)
        {
        }

        zce_byte    val;
    };
    struct IE_INT16
    {
        const static unsigned short IE_TYPE = E_IE_INT16;

        IE_INT16()
        :val(0)
        {
        }

        zce_int16    val;
    };
    struct IE_UINT16
    {
        const static unsigned short IE_TYPE = E_IE_UINT16;

        IE_UINT16()
        :val(0)
        {
        }

        zce_uint16    val;
    };
    struct IE_INT32
    {
        const static unsigned short IE_TYPE = E_IE_INT32;

        IE_INT32()
        :val(0)
        {
        }

        zce_int32    val;
    };
    struct IE_UINT32
    {
        const static unsigned short IE_TYPE = E_IE_UINT32;

        IE_UINT32()
        :val(0)
        {
        }

        zce_uint32    val;
    };
    struct IE_INT64
    {
        const static unsigned short IE_TYPE = E_IE_INT64;

        IE_INT64()
        :val(0)
        {
        }

        zce_int64    val;
    };
    struct IE_STRING254
    {
        const static unsigned short IE_TYPE = E_IE_STRING254;
        IE_STRING254() { };
        zce_string val;
    };
    struct IE_STRING
    {
        const static unsigned short IE_TYPE = E_IE_STRING;
        IE_STRING() { };
        zce_string val;
    };
    struct IE_STRING_UTF8
    {
        const static unsigned short IE_TYPE = E_IE_STRING_UTF8;
        IE_STRING_UTF8() { };
        zce_astring val;
    };
    struct IE_ANY
    {
        const static unsigned short IE_TYPE = E_IE_ANY;

        IE_ANY()
        :val(0)
        {
        }

        std::vector<zce_byte> val;
    };
    struct IE_INT64VEC
    {
        const static unsigned short IE_TYPE = E_IE_INT64VEC;

        IE_INT64VEC()
        :val(0)
        {
        }

        std::vector<zce_int64> val;
    };
    struct nspair_t
    {
        nspair_t() { };
        zce_astring name/*名*/;
        zce_astring value/*值*/;
    };
    struct IE_NSPAIR
    {
        const static unsigned short IE_TYPE = E_IE_NSPAIR;
        IE_NSPAIR() { };
        nspair_t    pair_t;
    };
    struct IE_NIPAIR
    {
        const static unsigned short IE_TYPE = E_IE_NIPAIR;

        IE_NIPAIR()
        :value(0)
        {
        }

        zce_astring name/*名*/;
        zce_int32    value/*值*/;
    };
    struct IE_NLLPAIR
    {
        const static unsigned short IE_TYPE = E_IE_NLLPAIR;

        IE_NLLPAIR()
        :value(0)
        {
        }

        zce_astring name/*名*/;
        zce_int64    value/*值*/;
    };
    struct IE_SITEID
    {
        const static unsigned short IE_TYPE = E_IE_SITEID;
        IE_SITEID() { };
        zce_astring val;
    };
    struct IE_NETADDR
    {
        const static unsigned short IE_TYPE = E_IE_NETADDR;
        IE_NETADDR() { };
        zdp_addr_t    addr_t;
    };
    struct MSG_NONE_REQ : public zce_smartptr_mtbase
    {
        const static unsigned short MSG_TYPE = E_MSG_NONE_REQ;
        static const char* type_name() { return ("MSG_NONE_REQ");}
        std::vector<IE_NSPAIR> ie_ns;
    };
    typedef zce_smartptr<MSG_NONE_REQ> MSG_NONE_REQ_PTR;

    struct MSG_CONN_REQ : public zce_smartptr_mtbase
    {
        const static unsigned short MSG_TYPE = E_MSG_CONN_REQ;
        static const char* type_name() { return ("MSG_CONN_REQ");}
        IE_UINT32    ie_id;
        IE_STRING254    ie_ip;
        IE_UINT16    ie_port;
        IE_ANY    ie_data;
        IE_UINT32    ie_maxconn;
        IE_UINT32    ie_period;
    };
    typedef zce_smartptr<MSG_CONN_REQ> MSG_CONN_REQ_PTR;

    struct MSG_DISCONN_REQ : public zce_smartptr_mtbase
    {
        const static unsigned short MSG_TYPE = E_MSG_DISCONN_REQ;
        static const char* type_name() { return ("MSG_DISCONN_REQ");}
    };
    typedef zce_smartptr<MSG_DISCONN_REQ> MSG_DISCONN_REQ_PTR;

} //namespace zdp_base
#endif //_zdp_base_proto_h_
